((topmost-intro <0,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((statement-cont <1,4>))
((brace-list-close <1,8>))
((statement <3,4>))
((statement-cont <1,4>))
((brace-list-intro <1,8>))
((brace-list-close <2,8>))
((statement <4,4>))
((statement-cont <1,4>))
((brace-list-intro <1,8>))
((brace-list-close <2,8>))
((statement <4,4>))
((statement-cont <1,4>))
((brace-list-intro <1,8>))
((brace-list-close <2,8>))
((statement <4,4>))
((statement-cont <1,4>))
((brace-list-close <1,8>))
((statement <3,4>))
((statement-cont <1,4>))
((arglist-close <1,8> <1,8>))
((statement <3,4>))
((statement-cont <1,4>))
((brace-list-intro <1,8>))
((brace-list-entry <1,12>))
((brace-list-entry <2,12>))
((brace-list-close <4,8>))
((statement <6,4>))
((statement-cont <1,4>))
((brace-list-intro <1,8>))
((brace-entry-open <1,12>))
((brace-list-close <3,8>))
((statement <5,4>))
((brace-list-open <1,4>))
((brace-list-intro <1,4>))
((brace-list-entry <1,8>))
((brace-list-close <3,4>))
((arglist-close <5,4> <5,20>))
((stream-op <6,4>))
((statement <7,4>))
((brace-list-entry <1,25>))
((brace-entry-open <2,25>))
((brace-list-intro <1,25>))
((brace-list-entry <1,29>))
((brace-list-entry <2,29>))
((brace-list-entry <3,29>))
((brace-list-entry <4,29>))
((brace-list-close <6,25>))
((brace-list-close <9,4>))
((statement <10,4>))
((defun-close <51,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((inclass <1,0>) (topmost-intro <1,0>))
((brace-list-open <1,4>))
((brace-list-close <1,4>))
((inclass <4,0>) (topmost-intro <1,0>))
((topmost-intro-cont <1,4>))
((template-args-cont <2,4> <1,4>))
((inclass <7,0>) (topmost-intro <1,0>))
((brace-list-open <1,4>))
((inclass <9,0>) (inline-open))
((class-close <10,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((statement-cont <1,4>))
((brace-list-intro <1,8>))
((brace-list-entry <1,12>))
((brace-list-close <3,8>))
((defun-close <6,0>))
