((topmost-intro <0,0>))
((inher-intro <1,0>))
((class-open <2,0>))
((inclass <1,0>) (access-label <1,0>))
((inclass <2,0>) (topmost-intro <2,0>))
((member-init-intro <1,4>))
((member-init-cont <1,10>))
((inclass <5,0>) (topmost-intro <1,0>))
((class-close <8,0>))
