((topmost-intro <0,0>))
((topmost-intro-cont <1,0>))
((knr-argdecl-intro <2,0>))
((knr-argdecl <1,0>))
((knr-argdecl <2,0>))
((defun-open <5,0>))
((defun-block-intro <1,0>))
((defun-close <2,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((topmost-intro-cont <1,0>))
((knr-argdecl <1,32>))
((knr-argdecl <2,32>))
((defun-open <4,0>))
((defun-block-intro <1,0>))
((defun-close <2,0>))
((topmost-intro <1,0>))
((topmost-intro <2,0>))
((topmost-intro-cont <1,0>))
((knr-argdecl-intro <2,0>))
((topmost-intro <1,0>))
((topmost-intro <1,0>))
((defun-open <1,0>))
((defun-block-intro <1,0>))
((defun-close <2,0>))
((topmost-intro <1,0>) (comment-intro))
((topmost-intro <2,0>) (comment-intro))
((topmost-intro <3,0>) (comment-intro))
