((topmost-intro <0,0>))
((defun-block-intro <1,0>))
((statement <1,4>))
((statement <2,4>))
((defun-block-intro <1,4>))
((statement <1,8>))
((inline-close <3,4>))
((statement <4,4>))
((statement <5,4>))
((statement <1,4>))
((statement <1,4>) (comment-intro))
((statement <2,4>) (comment-intro))
((statement <3,4>) (comment-intro))
((statement <4,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((statement <1,4>))
((statement <2,4>))
((statement <1,4>))
((statement <1,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((statement <4,4>))
((statement <1,4>))
((statement <1,4>))
((statement <1,4>))
((statement <2,4>) (comment-intro))
((statement <3,4>) (comment-intro))
((statement <4,4>) (comment-intro))
((statement <5,4>))
((statement <1,4>))
((statement <2,4>))
((inlambda) (defun-block-intro <1,4>))
((statement <2,4>))
((inlambda) (defun-block-intro <1,4>))
((statement <2,4>))
((statement <3,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (inline-close <2,4>))
((statement <3,4>))
((statement <4,4>))
((inlambda) (defun-block-intro <1,4>))
((inlambda) (defun-block-intro <2,4>))
((inlambda) (inline-close <3,4>))
((statement <4,4>))
((statement <1,4>))
((statement <1,4>))
((statement <1,4>))
((statement <2,4>))
((statement-cont <1,4>))
((arglist-intro <1,8> <1,8>))
((arglist-cont <1,12>))
((arglist-cont <2,12>))
((arglist-intro <1,12> <1,18>))
((arglist-close <2,12> <2,18>))
((arglist-cont <5,12>))
((arglist-cont <6,12>))
((arglist-cont <7,12>))
((inlambda) (inline-open <6,12>))
((defun-block-intro <1,18>))
((inline-close <2,18>))
((arglist-cont <11,12>))
((arglist-close <13,8> <13,8>))
((statement-cont <15,4>))
((statement-cont <16,4>))
((statement-cont <17,4>))
((statement-cont <18,4>))
((inline-open <18,8>))
((defun-block-intro <1,8>))
((inline-close <2,8>))
((defun-close <84,0>))
